In [1]:
#Load dataset
import pandas as pd
import numpy as np
df = pd.read_csv('merge.csv')
df.sort_values('Area Code (FAO)')
df

Area Code (FAO)  Year  population   yield  harvested   Value
0                   2  1961      0.0060  0.0917     0.0318  0.0170
1                   2  1962      0.0061  0.0871     0.0333  0.0170
2                   2  1963      0.0062  0.0738     0.0333  0.0145
3                   2  1964      0.0064  0.0850     0.0334  0.0166
4                   2  1965      0.0065  0.0870     0.0334  0.0170
...               ...   ...         ...     ...        ...     ...
6608              181  2016      0.0099  0.1745     0.0003  0.0003
6609              181  2017      0.0101  0.1606     0.0003  0.0003
6610              181  2018      0.0103  0.1481     0.0004  0.0003
6611              181  2019      0.0105  0.1676     0.0006  0.0006
6612              181  2020      0.0107  0.1676     0.0012  0.0011

[6613 rows x 6 columns]

In [2]:
#clear rows whithout 60 years
d=(df.groupby('Area Code (FAO)').count()==60)[['Year']]
d=list(d[d['Year']==True].reset_index()['Area Code (FAO)'])
for i in range(len(df)):
    if df['Area Code (FAO)'][i] not in d:
        df.drop(i,axis=0,inplace=True)
df

Area Code (FAO)  Year  population   yield  harvested   Value
0                   2  1961      0.0060  0.0917     0.0318  0.0170
1                   2  1962      0.0061  0.0871     0.0333  0.0170
2                   2  1963      0.0062  0.0738     0.0333  0.0145
3                   2  1964      0.0064  0.0850     0.0334  0.0166
4                   2  1965      0.0065  0.0870     0.0334  0.0170
...               ...   ...         ...     ...        ...     ...
6608              181  2016      0.0099  0.1745     0.0003  0.0003
6609              181  2017      0.0101  0.1606     0.0003  0.0003
6610              181  2018      0.0103  0.1481     0.0004  0.0003
6611              181  2019      0.0105  0.1676     0.0006  0.0006
6612              181  2020      0.0107  0.1676     0.0012  0.0011

[4980 rows x 6 columns]

In [3]:
(df.groupby('Area Code (FAO)').count()==60).sum()
Y=df['Value']
Y=np.array(Y)
Y=Y.reshape(83,1,60)
Y.shape

(83, 1, 60)

In [4]:
df.duplicated().sum()

0

In [5]:
arr=np.array([])

#create a 2d array for population that each rows show populations for a country
population=df.loc[:,"population"]
population=population.values.tolist()
population=np.array(population)
population=population.reshape(83,60)
print(population)


#create a 2d array for yield that each rows show yields for a country
Yield=df.loc[:,"yield"]
Yield=Yield.values.tolist()
Yield=np.array(Yield)
Yield=Yield.reshape(83,60)

#create a 2d array for harvested that each rows show harvesteds for a country
harvested=df.loc[:,"harvested"]
harvested=harvested.values.tolist()
harvested=np.array(harvested)
harvested=harvested.reshape(83,60)

#create a 2d array for production that each rows show productions for a country
#production=df.loc[:,"production"]
#production=production.values.tolist()
#production=np.array(production)
#production=production.reshape(83,60)


#create a 1d array that we will make it to a 3d array
for i in range(83):
    arr=np.append(arr,population[i])
    arr=np.append(arr,Yield[i])
    arr=np.append(arr,harvested[i])
    #arr=np.append(arr,production[i])

#reshape 1d array to a 3d array that each dimension is for a country , culomn for years , and rows for values
arr=arr.reshape(83,3,60)
arr


[[0.006  0.0061 0.0062 ... 0.0251 0.0259 0.0267]
 [0.0012 0.0012 0.0012 ... 0.0019 0.0019 0.0019]
 [0.0079 0.008  0.0082 ... 0.0287 0.0293 0.0298]
 ...
 [0.0038 0.0039 0.004  ... 0.0211 0.0216 0.0221]
 [0.0022 0.0022 0.0023 ... 0.0122 0.0126 0.0129]
 [0.0026 0.0027 0.0028 ... 0.0103 0.0105 0.0107]]


array([[[6.000e-03, 6.100e-03, 6.200e-03, ..., 2.510e-02, 2.590e-02,
         2.670e-02],
        [9.170e-02, 8.710e-02, 7.380e-02, ..., 2.036e-01, 1.927e-01,
         1.785e-01],
        [3.180e-02, 3.330e-02, 3.330e-02, ..., 2.330e-02, 3.320e-02,
         3.800e-02]],

       [[1.200e-03, 1.200e-03, 1.200e-03, ..., 1.900e-03, 1.900e-03,
         1.900e-03],
        [6.830e-02, 9.450e-02, 6.260e-02, ..., 3.432e-01, 3.785e-01,
         4.029e-01],
        [1.800e-03, 2.000e-03, 1.200e-03, ..., 9.000e-04, 8.000e-04,
         8.000e-04]],

       [[7.900e-03, 8.000e-03, 8.200e-03, ..., 2.870e-02, 2.930e-02,
         2.980e-02],
        [3.370e-02, 7.120e-02, 7.390e-02, ..., 1.879e-01, 1.803e-01,
         1.538e-01],
        [2.410e-02, 2.670e-02, 2.720e-02, ..., 2.780e-02, 2.810e-02,
         2.630e-02]],

       ...,

       [[3.800e-03, 3.900e-03, 4.000e-03, ..., 2.110e-02, 2.160e-02,
         2.210e-02],
        [1.186e-01, 1.175e-01, 1.177e-01, ..., 1.304e-01, 1.599e-01,
         1.6

In [6]:
from sklearn.preprocessing import StandardScaler
scalers={}
for i in range(arr.shape[1]):
    scalers[i]=StandardScaler()
    arr[:,i,:] = scalers[i].fit_transform(arr[:,i,:])

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(arr,Y, test_size=0.2)
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(66, 3, 60) (17, 3, 60) (66, 1, 60) (17, 1, 60)


In [8]:
#Reshape X_train and X_test
X_train = X_train.reshape(X_train.shape[0], 3, 60, 1)
X_test = X_test.reshape(X_test.shape[0], 3, 60, 1)

X_train.shape, X_test.shape

((66, 3, 60, 1), (17, 3, 60, 1))

In [11]:
!pip install keras-tuner -q

     |████████████████████████████████| 135 kB 5.0 MB/s 
     |████████████████████████████████| 1.6 MB 30.6 MB/s 


In [12]:
from keras.models import Sequential

from tensorflow import keras
from keras.layers import Flatten, Dense, Conv2D, MaxPooling2D,Input
from keras import layers, Model
from keras_tuner.tuners import RandomSearch

In [13]:
model=Sequential()
model.add(Conv2D(32,kernel_size=(3,5),activation='relu',input_shape=(3,60,1),padding='same'))
model.add(MaxPooling2D(padding='same'))

model.add(Conv2D(64,kernel_size=(3,5),activation='relu',padding='same'))
model.add(MaxPooling2D(padding='same'))

model.add(Flatten())

model.add(Dense(60,activation='relu'))
model.compile(loss='mean_absolute_percentage_error',metrics=['mean_absolute_percentage_error'],optimizer='adam')

model.fit(X_train,Y_train,epochs=1000,batch_size=1,validation_data=(X_test,Y_test))




Epoch 1/1000
66/66 [==============================] - 2s 8ms/step - loss: 78682.9062 - mean_absolute_percentage_error: 78682.9062 - val_loss: 80.9804 - val_mean_absolute_percentage_error: 80.9804
Epoch 2/1000
66/66 [==============================] - 0s 5ms/step - loss: 86.1616 - mean_absolute_percentage_error: 86.1616 - val_loss: 80.9804 - val_mean_absolute_percentage_error: 80.9804
Epoch 3/1000
66/66 [==============================] - 0s 8ms/step - loss: 86.1616 - mean_absolute_percentage_error: 86.1616 - val_loss: 80.9804 - val_mean_absolute_percentage_error: 80.9804
Epoch 4/1000
66/66 [==============================] - 0s 6ms/step - loss: 86.1616 - mean_absolute_percentage_error: 86.1616 - val_loss: 80.9804 - val_mean_absolute_percentage_error: 80.9804
Epoch 5/1000
66/66 [==============================] - 0s 6ms/step - loss: 86.1616 - mean_absolute_percentage_error: 86.1616 - val_loss: 80.9804 - val_mean_absolute_percentage_error: 80.9804
Epoch 6/1000
66/66 [========================

In [14]:
pip install alibi[tensorflow]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 472 kB 5.4 MB/s 
     |████████████████████████████████| 5.8 MB 42.8 MB/s 
     |████████████████████████████████| 98.5 MB 85 kB/s 
     |████████████████████████████████| 7.6 MB 35.0 MB/s 
     |████████████████████████████████| 182 kB 45.2 MB/s 


In [15]:
import tensorflow as tf
from alibi.explainers import IntegratedGradients

ig  = IntegratedGradients(model,
                          layer=None,
                          method="gausslegendre",
                          n_steps=50,
                          internal_batch_size=100)

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [50]:
explanation_train = ig.explain(X_train,
                         baselines=None,
                         target=None)

attributions_train = explanation_train.attributions

ValueError: ignored

In [ ]:
explanation_train

In [48]:
attributions_train

In [ ]:
explanation_test = ig.explain(X_test,
                         baselines=None,
                         target=None)

attributions_test = explanation_test.attributions

In [49]:
#Write ig result tp file
file = open('ig_train.txt','w')
for item in attributions_train:
	file.write(attributions_train+"\n")
file.close()

file2 = open('ig_test.txt','w')
for item in attributions_test:
	file2.write(item+"\n")
file2.close()