In [3]:
#Load dataset
import pandas as pd
import numpy as np
df = pd.read_csv('merge.csv')
df.sort_values('Area Code (FAO)')
df

Area Code (FAO)  Year  population  yield  harvested      Value
0                   2  1961    8790.140  10220  2230000.0  2279000.0
1                   2  1962    8969.047   9735  2341000.0  2279000.0
2                   2  1963    9157.465   8317  2341000.0  1947000.0
3                   2  1964    9355.514   9510  2345000.0  2230000.0
4                   2  1965    9565.147   9723  2347000.0  2282000.0
...               ...   ...         ...    ...        ...        ...
6608              181  2016   14452.704  19013    22094.0    42008.0
6609              181  2017   14751.101  17542    22070.0    38715.0
6610              181  2018   15052.184  16206    27767.0    45000.0
6611              181  2019   15354.608  18278    43769.0    80000.0
6612              181  2020   15669.666  18278    82068.0   150000.0

[6613 rows x 6 columns]

In [4]:
#clear rows whithout 60 years
d=(df.groupby('Area Code (FAO)').count()==60)[['Year']]
d=list(d[d['Year']==True].reset_index()['Area Code (FAO)'])
for i in range(len(df)):
    if df['Area Code (FAO)'][i] not in d:
        df.drop(i,axis=0,inplace=True)
df

Area Code (FAO)  Year  population  yield  harvested      Value
0                   2  1961    8790.140  10220  2230000.0  2279000.0
1                   2  1962    8969.047   9735  2341000.0  2279000.0
2                   2  1963    9157.465   8317  2341000.0  1947000.0
3                   2  1964    9355.514   9510  2345000.0  2230000.0
4                   2  1965    9565.147   9723  2347000.0  2282000.0
...               ...   ...         ...    ...        ...        ...
6608              181  2016   14452.704  19013    22094.0    42008.0
6609              181  2017   14751.101  17542    22070.0    38715.0
6610              181  2018   15052.184  16206    27767.0    45000.0
6611              181  2019   15354.608  18278    43769.0    80000.0
6612              181  2020   15669.666  18278    82068.0   150000.0

[4980 rows x 6 columns]

In [5]:
(df.groupby('Area Code (FAO)').count()==60).sum()
Y=df['Value']
Y=np.array(Y)
Y=Y.reshape(83,1,60)
Y.shape

(83, 1, 60)

In [6]:
df.duplicated().sum()

0

In [7]:
arr=np.array([])

#create a 2d array for population that each rows show populations for a country
population=df.loc[:,"population"]
population=population.values.tolist()
population=np.array(population)
population=population.reshape(83,60)
print(population)


#create a 2d array for yield that each rows show yields for a country
Yield=df.loc[:,"yield"]
Yield=Yield.values.tolist()
Yield=np.array(Yield)
Yield=Yield.reshape(83,60)

#create a 2d array for harvested that each rows show harvesteds for a country
harvested=df.loc[:,"harvested"]
harvested=harvested.values.tolist()
harvested=np.array(harvested)
harvested=harvested.reshape(83,60)



#create a 1d array that we will make it to a 3d array
for i in range(83):
    arr=np.append(arr,population[i])
    arr=np.append(arr,Yield[i])
    arr=np.append(arr,harvested[i])
    #arr=np.append(arr,production[i])

#reshape 1d array to a 3d array that each dimension is for a country , culomn for years , and rows for values
arr=arr.reshape(83,3,60)
arr


[[ 8790.14   8969.047  9157.465 ... 36686.784 37769.499 38972.23 ]
 [ 1769.079  1828.232  1888.302 ...  2877.013  2873.883  2866.849]
 [11598.608 11778.26  11969.451 ... 41927.007 42705.368 43451.666]
 ...
 [ 5646.668  5753.386  5860.197 ... 30790.513 31546.691 32284.046]
 [ 3219.451  3323.427  3431.381 ... 17835.893 18380.477 18927.715]
 [ 3925.952  4049.778  4177.931 ... 15052.184 15354.608 15669.666]]


array([[[8.7901400e+03, 8.9690470e+03, 9.1574650e+03, ...,
         3.6686784e+04, 3.7769499e+04, 3.8972230e+04],
        [1.0220000e+04, 9.7350000e+03, 8.3170000e+03, ...,
         2.2100000e+04, 2.0951000e+04, 1.9434000e+04],
        [2.2300000e+06, 2.3410000e+06, 2.3410000e+06, ...,
         1.6350000e+06, 2.3340000e+06, 2.6680000e+06]],

       [[1.7690790e+03, 1.8282320e+03, 1.8883020e+03, ...,
         2.8770130e+03, 2.8738830e+03, 2.8668490e+03],
        [7.7310000e+03, 1.0522000e+04, 7.1270000e+03, ...,
         3.6927000e+04, 4.0680000e+04, 4.3271000e+04],
        [1.2650000e+05, 1.3914400e+05, 8.6660000e+04, ...,
         6.5072000e+04, 5.7330000e+04, 5.3946000e+04]],

       [[1.1598608e+04, 1.1778260e+04, 1.1969451e+04, ...,
         4.1927007e+04, 4.2705368e+04, 4.3451666e+04],
        [4.0600000e+03, 8.0450000e+03, 8.3260000e+03, ...,
         2.0433000e+04, 1.9630000e+04, 1.6811000e+04],
        [1.6890640e+06, 1.8733000e+06, 1.9092030e+06, ...,
         1.9484020e+06, 1

In [8]:
#preproccessing dataset 
from sklearn.preprocessing import StandardScaler
scalers={}
for i in range(arr.shape[1]):
    scalers[i]=StandardScaler()
    arr[:,i,:] = scalers[i].fit_transform(arr[:,i,:])

In [9]:
#split dataset into train and test parts
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(arr,Y, test_size=0.2)
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(66, 3, 60) (17, 3, 60) (66, 1, 60) (17, 1, 60)


In [10]:
#Reshape X_train and X_test
X_train = X_train.reshape(X_train.shape[0], 3, 60, 1)
X_test = X_test.reshape(X_test.shape[0], 3, 60, 1)

X_train.shape, X_test.shape

((66, 3, 60, 1), (17, 3, 60, 1))

In [11]:
!pip install keras-tuner -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.7/135.7 KB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 27.5 MB/s eta 0:00:00


In [12]:
from keras.models import Sequential

from tensorflow import keras
from keras.layers import Flatten, Dense, Conv2D, MaxPooling2D,Input
from keras import layers, Model
from keras_tuner.tuners import RandomSearch

In [13]:
#create convolutional layers and fit the model 
model=Sequential()
model.add(Conv2D(32,kernel_size=(3,5),activation='relu',input_shape=(3,60,1),padding='same'))
model.add(MaxPooling2D(padding='same'))

model.add(Conv2D(64,kernel_size=(3,5),activation='relu',padding='same'))
model.add(MaxPooling2D(padding='same'))

model.add(Flatten())
model.add(Dense(960))
model.add(Dense(60))
model.compile(loss='mean_absolute_percentage_error',metrics=['mean_absolute_percentage_error'],optimizer='adam')

model.fit(X_train,Y_train,epochs=32,batch_size=1,validation_data=(X_test,Y_test))




Epoch 1/32
66/66 [==============================] - 2s 12ms/step - loss: 97.6666 - mean_absolute_percentage_error: 97.6666 - val_loss: 97.0448 - val_mean_absolute_percentage_error: 97.0448
Epoch 2/32
66/66 [==============================] - 1s 11ms/step - loss: 97.0385 - mean_absolute_percentage_error: 97.0385 - val_loss: 98.6522 - val_mean_absolute_percentage_error: 98.6522
Epoch 3/32
66/66 [==============================] - 1s 9ms/step - loss: 96.2946 - mean_absolute_percentage_error: 96.2946 - val_loss: 96.9327 - val_mean_absolute_percentage_error: 96.9327
Epoch 4/32
66/66 [==============================] - 1s 9ms/step - loss: 95.7432 - mean_absolute_percentage_error: 95.7432 - val_loss: 98.5515 - val_mean_absolute_percentage_error: 98.5515
Epoch 5/32
66/66 [==============================] - 1s 9ms/step - loss: 95.2951 - mean_absolute_percentage_error: 95.2951 - val_loss: 98.3431 - val_mean_absolute_percentage_error: 98.3431
Epoch 6/32
66/66 [==============================] - 1s 10m

# New Section

In [14]:
pip install alibi[tensorflow]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 523.0/523.0 KB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 69.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.5/98.5 MB 10.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.4/182.4 KB 19.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 87.9 MB/s eta 0:00:00


In [15]:
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(66, 3, 60, 1) (17, 3, 60, 1) (66, 1, 60) (17, 1, 60)


In [16]:
import tensorflow as tf
from alibi.explainers import IntegratedGradients
from functools import partial

target_fn=partial(np.argmax, axis=1)

ig=IntegratedGradients(model, target_fn=target_fn)
explanations=ig.explain(arr)



/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [17]:

attributions = explanations.attributions
ig = attributions[0]

In [21]:
from numpy import asarray
from numpy import savetxt
print(ig.reshape(83*3,60))
savetxt('igdata.csv', ig.reshape(83*3,60))

[[-9.46267089e-01 -5.54101040e-01  7.29938746e-01 ... -7.90953320e-01
   2.07840321e+00 -1.11570792e+00]
 [-2.00044336e+00 -8.83577301e+00 -2.63178131e+01 ...  7.89449319e+00
   3.53325128e+01  5.47415136e+01]
 [-1.00179872e-01  1.78071550e+00  7.17539370e-01 ...  1.50536395e+00
   9.14314817e-01 -1.00758131e+00]
 ...
 [-2.00863185e+00 -1.13042795e+00 -3.30085803e+00 ... -1.87092686e+00
  -8.29437367e-01  2.84857354e-01]
 [ 6.61368940e-01  1.28113295e+00  3.90162631e+00 ...  1.06862044e+02
   2.64232056e+01  4.65951691e+01]
 [-2.84804876e+00 -2.30400072e+00 -4.82537245e+00 ...  5.02072687e+00
   6.31814208e+00  3.73290572e+00]]


In [22]:
print(arr.shape)
print(ig.shape)
print(Y.shape)


(83, 3, 60)
(83, 3, 60)
(83, 1, 60)


In [23]:
def row(before):
  kernel = np.ones(5)/5
  after = np.convolve(before,kernel,mode="same")
  return after


def country(before):
  after = np.empty((3,60))
  for i in range(3):
    after[i,0:60] = row(before[i])
  return after



xavg = np.empty((83,3,60))
yavg = np.empty((83,1,60))
igavg = np.empty((83,3,60))

for i in range(83):
  xavg[i,0:3,0:83] = country(arr[i])

for i in range(83):
  igavg[i,0:3,0:83] = country(ig[i])


for i in range(83):
  yavg[i,0:1,0:83] = row(np.squeeze(Y[i]))


xavg = xavg.reshape(83,60,3)
yavg = yavg.reshape(83,60,1)
igavg = igavg.reshape(83,60,3)


x_per_year = np.hsplit(xavg,60)
y_per_year = np.hsplit(yavg,60)
ig_per_year = np.hsplit(igavg,60)


for i in range(60):
  x_per_year[i] = x_per_year[i].reshape(83,3)
  y_per_year[i] = y_per_year[i].reshape(83,1)
  ig_per_year[i] = ig_per_year[i].reshape(83,3)


combine = np.empty((83*60,7))
for i in range(60):
  data_per_year = np.array(np.concatenate((np.stack((x_per_year[i],ig_per_year[i]),axis=2).reshape(83,6),y_per_year[i]),axis=1))
  for j in range(83):
    combine[i*83+j,0:7] = data_per_year[j]

print(combine[0])

[-1.42401884e-01 -1.54085877e-01 -1.89578430e-01 -5.19057425e-01
 -2.36586131e-01 -7.31338411e-01  1.30100000e+06]


In [24]:
savetxt('combinedata.csv', combine)